/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // 高级灰 - 更柔和的现代配色
        stone: {
          50: '#fafaf9',
          100: '#f5f5f4',
          200: '#e7e5e4',
          300: '#d6d3d1',
          400: '#a8a29e',
          500: '#78716c',
          600: '#57534e',
          700: '#44403c',
          800: '#292524',
          900: '#1c1917',
          950: '#0c0a09',
        },
        // 精致蓝 - 更柔和的蓝色调
        sky: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        // 精致紫 - 更柔和的紫色调
        violet: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
        // 精致绿 - 柔和的绿色调
        emerald: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        accent: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        serif: ['Georgia', 'Times New Roman', 'serif'],
        mono: ['JetBrains Mono', 'Monaco', 'Consolas', 'monospace'],
        display: ['Cal Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.6rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.1' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
        '7xl': ['4.5rem', { lineHeight: '1.1' }],
        '8xl': ['6rem', { lineHeight: '1.1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.02)',
        DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.03), 0 2px 4px -2px rgb(0 0 0 / 0.03)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.02), 0 4px 6px -4px rgb(0 0 0 / 0.02)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.02), 0 8px 10px -6px rgb(0 0 0 / 0.02)',
        '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.08)',
        '3xl': '0 35px 60px -15px rgb(0 0 0 / 0.06)',
        inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.02)',
        none: 'none',
        // 精致阴影 - 更柔和的效果
        'elegant': '0 8px 40px rgba(0, 0, 0, 0.04)',
        'elegant-lg': '0 16px 60px rgba(0, 0, 0, 0.06)',
        'elegant-xl': '0 24px 80px rgba(0, 0, 0, 0.08)',
        // 精致发光效果
        'glow': '0 0 40px rgba(14, 165, 233, 0.1)',
        'glow-lg': '0 0 60px rgba(168, 85, 247, 0.15)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
        '4xl': '4rem',
        full: '9999px',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: '70ch',
            color: theme('colors.stone.700'),
            lineHeight: '1.75',
            '[class~="lead"]': {
              color: theme('colors.stone.600'),
              fontSize: '1.25em',
              lineHeight: '1.6',
            },
            a: {
              color: theme('colors.sky.600'),
              textDecoration: 'none',
              fontWeight: '500',
              '&:hover': {
                color: theme('colors.sky.700'),
                textDecoration: 'underline',
              },
            },
            strong: {
              color: theme('colors.stone.900'),
              fontWeight: '600',
            },
            'ol > li::marker': {
              color: theme('colors.stone.500'),
            },
            'ul > li::marker': {
              color: theme('colors.stone.500'),
            },
            hr: {
              borderColor: theme('colors.stone.200'),
              borderTopWidth: '1px',
              marginTop: '3em',
              marginBottom: '3em',
            },
            blockquote: {
              fontWeight: '500',
              fontStyle: 'italic',
              color: theme('colors.stone.800'),
              borderLeftWidth: '0.25rem',
              borderLeftColor: theme('colors.stone.300'),
              quotes: '"\\201C""\\201D""\\2018""\\2019"',
              marginTop: '2em',
              marginBottom: '2em',
              paddingLeft: '1.5em',
              paddingRight: '1em',
              backgroundColor: theme('colors.stone.50'),
              borderRadius: '0.5rem',
            },
            'blockquote p:first-of-type::before': {
              content: 'open-quote',
            },
            'blockquote p:last-of-type::after': {
              content: 'close-quote',
            },
            h1: {
              color: theme('colors.stone.900'),
              fontWeight: '800',
              fontSize: '2.5em',
              marginTop: '0',
              marginBottom: '1em',
              lineHeight: '1.2',
              letterSpacing: '-0.025em',
            },
            h2: {
              color: theme('colors.stone.900'),
              fontWeight: '700',
              fontSize: '1.8em',
              marginTop: '2.5em',
              marginBottom: '1em',
              lineHeight: '1.3',
              letterSpacing: '-0.02em',
            },
            h3: {
              color: theme('colors.stone.900'),
              fontWeight: '600',
              fontSize: '1.4em',
              marginTop: '2em',
              marginBottom: '0.8em',
              lineHeight: '1.4',
              letterSpacing: '-0.015em',
            },
            h4: {
              color: theme('colors.stone.900'),
              fontWeight: '600',
              marginTop: '1.8em',
              marginBottom: '0.6em',
              lineHeight: '1.4',
            },
            code: {
              color: theme('colors.stone.900'),
              fontWeight: '500',
              backgroundColor: theme('colors.stone.100'),
              padding: '0.25em 0.5em',
              borderRadius: '0.375rem',
              fontSize: '0.9em',
              border: '1px solid',
              borderColor: theme('colors.stone.200'),
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              backgroundColor: theme('colors.stone.900'),
              color: theme('colors.stone.50'),
              borderRadius: '1rem',
              padding: '1.5rem',
              overflowX: 'auto',
              fontSize: '0.9em',
              lineHeight: '1.6',
              marginTop: '2em',
              marginBottom: '2em',
              boxShadow: '0 8px 40px rgba(0, 0, 0, 0.1)',
            },
            'pre code': {
              backgroundColor: 'transparent',
              borderWidth: '0',
              borderRadius: '0',
              padding: '0',
              fontWeight: '400',
              color: 'inherit',
              fontSize: 'inherit',
              fontFamily: 'inherit',
              lineHeight: 'inherit',
            },
            'pre code::before': {
              content: '""',
            },
            'pre code::after': {
              content: '""',
            },
            table: {
              width: '100%',
              tableLayout: 'auto',
              textAlign: 'left',
              marginTop: '2em',
              marginBottom: '2em',
              fontSize: '0.9em',
              lineHeight: '1.6',
            },
            thead: {
              color: theme('colors.stone.900'),
              fontWeight: '600',
              borderBottomWidth: '2px',
              borderBottomColor: theme('colors.stone.200'),
            },
            'thead th': {
              verticalAlign: 'bottom',
              padding: '0.75em 1em',
            },
            'tbody tr': {
              borderBottomWidth: '1px',
              borderBottomColor: theme('colors.stone.100'),
            },
            'tbody tr:last-child': {
              borderBottomWidth: '0',
            },
            'tbody td': {
              verticalAlign: 'top',
              padding: '0.75em 1em',
            },
          },
        },
        dark: {
          css: {
            color: theme('colors.stone.300'),
            '[class~="lead"]': {
              color: theme('colors.stone.400'),
            },
            a: {
              color: theme('colors.sky.400'),
              '&:hover': {
                color: theme('colors.sky.300'),
              },
            },
            strong: {
              color: theme('colors.stone.100'),
            },
            'ol > li::marker': {
              color: theme('colors.stone.400'),
            },
            'ul > li::marker': {
              color: theme('colors.stone.400'),
            },
            hr: {
              borderColor: theme('colors.stone.700'),
            },
            blockquote: {
              color: theme('colors.stone.100'),
              borderLeftColor: theme('colors.stone.600'),
              backgroundColor: theme('colors.stone.800'),
            },
            h1: {
              color: theme('colors.stone.100'),
            },
            h2: {
              color: theme('colors.stone.100'),
            },
            h3: {
              color: theme('colors.stone.100'),
            },
            h4: {
              color: theme('colors.stone.100'),
            },
            code: {
              color: theme('colors.stone.100'),
              backgroundColor: theme('colors.stone.800'),
              borderColor: theme('colors.stone.700'),
            },
            pre: {
              backgroundColor: theme('colors.stone.900'),
            },
            thead: {
              color: theme('colors.stone.100'),
              borderBottomColor: theme('colors.stone.700'),
            },
            'tbody tr': {
              borderBottomColor: theme('colors.stone.800'),
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}