# Header
menu:
  主页: /
  归档: /archives
  关于: /about

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: 
google_adsense: 
favicon: /favicon.ico
twitter: 
github: 
rss: /atom.xml